Add implementations of equals()/hashCode() for views of THashMap
JetBrains/intellij-deps-trove4j pull request #4
Opened 2020-05-02 22:31 UTC by serejke

`THashMap.keySet()` appeared to miss implementation of `equals()/hashCode()`.
I hit a bug comparing keys of two maps:
```
Map<K, V> one
Map<K, V> two
// This assertion fails if one or two is THashMap.
assertEquals(one.keySet(), two.keySet());
```

2020-05-03 10:42 UTC, develar commented
I think it is time to stop using this outdated and not maintained library.
Numerous times this topic was raised and I think we should make decision.

On Sun, 3 May 2020, 00:32 Sergey Patrikeev, <notifications@github.com>
wrote:

> THashMap.keySet() appeared to miss implementation of equals()/hashCode().
> I hit a bug comparing keys of two maps:
>
> Map<K, V> one
> Map<K, V> two
> // This assertion fails if one or two is THashMap.
> assertEquals(one.keySet(), two.keySet());
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/JetBrains/intellij-deps-trove4j/pull/4
> Commit Summary
>
>    - Add implementations of equals()/hashCode() for views of THashMap:
>    keySet(), values(), entrySet().
>
> File Changes
>
>    - *M* core/src/main/java/gnu/trove/THashMap.java
>    <https://github.com/JetBrains/intellij-deps-trove4j/pull/4/files#diff-ff95a2c6b7606a028a55d14bda9da6d7>
>    (28)
>    - *M* core/src/test/java/gnu/trove/MapTest.java
>    <https://github.com/JetBrains/intellij-deps-trove4j/pull/4/files#diff-5623d13c1d41c52635f3942b1e3aef5f>
>    (26)
>    - *M* gradle.properties
>    <https://github.com/JetBrains/intellij-deps-trove4j/pull/4/files#diff-503f218d646c10f484fdc9d6315bf2e3>
>    (2)
>    - *M* trove4j_changes.txt
>    <https://github.com/JetBrains/intellij-deps-trove4j/pull/4/files#diff-df5d2a6229a85bb6baa4e66d67d1936e>
>    (3)
>
> Patch Links:
>
>    - https://github.com/JetBrains/intellij-deps-trove4j/pull/4.patch
>    - https://github.com/JetBrains/intellij-deps-trove4j/pull/4.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JetBrains/intellij-deps-trove4j/pull/4>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACVTXWIVDUSNHFAQM7F653RPSNOLANCNFSM4MX3TMSQ>
> .
>

2020-05-03 11:25 UTC, serejke commented
I totally agree. It doesn't seem production-quality. Especially, the concern is the lack of full-covering tests.
But as soon as migration might be hard and lengthy (as I got from previous discussions), I believe, bug fixes still make sense.

2020-05-04 03:14 UTC, amaembo requested changes

2020-05-04 03:14 UTC, amaembo commented on core/src/main/java/gnu/trove/THashMap.java
> +                if (!(key == otherKey || key != null && _hashingStrategy.equals(key, (K) otherKey))) {
This implementation violates the `Entry` spec. It's written in the spec how exactly keys and values should be compared:

> Compares the specified object with this entry for equality. Returns true if the given object is also a map entry and the two entries represent the same mapping. More formally, two entries e1 and e2 represent the same mapping if
> ```java
>               (e1.getKey()==null ?
>                e2.getKey()==null : e1.getKey().equals(e2.getKey()))  &&
>               (e1.getValue()==null ?
>                e2.getValue()==null : e1.getValue().equals(e2.getValue()))
> ```
> This ensures that the equals method works properly across different implementations of the Map.Entry interface.

Moreover, this `equals` implementation violates the general contract for `Object.equals`. If compared with `Map.Entry` that comes from another Map, the hashingStrategy of this Map will be used, so it's possible to violate the symmetry of equals (a.equals(b) != b.equals(a)). Is it really necessary to use hashingStrategy here? 

We can compare hashingStrategy with custom comparator of the `TreeMap`. The custom comparator may be inconsistent with `equals`. Yet, `TreeMap.Entry` doesn't use the comparator to compare entries. Instead, it fulfills the `equals` contract. Also, `TreeMap.EntrySet` implementation delegates its equals to `AbstractSet` like you are doing, and it looks like everybody is fine with this. I suggest to reuse that experience here as well: ignore hashing strategy when comparing views.

2020-05-04 03:14 UTC, amaembo commented on core/src/main/java/gnu/trove/THashMap.java
> +            hashProcedure.execute(key, val);
The `Map.Entry.hashCode` is also fully specified:

> Returns the hash code value for this map entry. The hash code of a map entry e is defined to be:
> ```java
>               (e.getKey()==null   ? 0 : e.getKey().hashCode()) ^
>               (e.getValue()==null ? 0 : e.getValue().hashCode())
> ```           
> This ensures that `e1.equals(e2)` implies that `e1.hashCode()==e2.hashCode()` for any two Entries `e1` and `e2`, as required by the general contract of `Object.hashCode`.

I don't think the `HashProcedure` will produce the same algorithm. Please write it according to the spec:

```java
int keyHash = (key==null ? 0 : key.hashCode());
int valueHash = (val==null ? 0 : val.hashCode());
return keyHash ^ valueHash;
```

2020-05-04 03:14 UTC, amaembo commented on core/src/test/java/gnu/trove/MapTest.java
> +      THashMap<String, Integer> twoMap = new THashMap<String, Integer>();
It would be good to compare with non-THashMap implementation (e.g. usual HashMap) in test as well.

2020-05-04 08:42 UTC, develar commented
@serejke Where do you use it? Maybe you can use fastutil instead?

2020-05-09 10:44 UTC, serejke commented
@develar THashMaps are widely used in IDE indexes. I wanted to compare two `Map<K, V>`-s produced by `DataIndexer` and caught this bug. In the new code I will consider using `fastutil`.

2020-05-09 10:52 UTC, serejke commented
@amaembo Thank you for careful code review and pointing to Javadoc.

Indeed, we can assert that hashing strategy is "consistent with equals" (term from Javadoc) and compare keys using default `.equals()`.

All suggestions have been applied. New tests have been added.

On the way I caught one more bug: `THashMap.values()` used to inherit `MapBackedView` that was `Set`, which is incorrect because `.values()` must be a `Collection` (to allow value duplicates for different keys). Got rid of `MapBackedView` and inherited `AbstractSet` / `AbstractCollection` independently.

2020-05-10 08:30 UTC, develar commented
fastutil available for use in platform. https://docs.google.com/document/d/1qJztRa3u2VKfzDH4jqFMtUAWAPr7rljKMg5PexuOwxg/edit

2020-05-11 03:02 UTC, amaembo approved these changes
Looks good in general. If you decide to implement clear(), additional review round may be skipped as it's pretty straightforward.

2020-05-11 03:02 UTC, amaembo commented on core/src/main/java/gnu/trove/THashMap.java
> -            THashMap.this.clear();
I would suggest to implement `clear()` as well. `AbstractCollection.clear()` implementation is slow.

2022-06-07 10:57 UTC, closed without merging